### ISSUE TITLE
what do I need to install to make it build?

### ISSUE THREAD

**Issue by mcr** [anima-wg/voucher#2]
cd refs; ./gen-trees.sh; cd ..;
    ../ietf-voucher@2016-10-27.yang:8: error: module "ietf-yang-types" not found in search path
    ../ietf-voucher@2017-01-09.yang:98: error: unterminated statement definition for keyword "description", looking at '
    ../ietf-voucher-revocation@2016-10-27.yang:8: error: module "ietf-yang-types" not found in search path

**Comment by kwatsen** [comment]
Micheal,

The makefile itself lists everything. 

Otherwise, be sure to re-initialize the pyang environment whenever using a new shell.   for instance: cd <pyang-dir>; . env.sh; cd --

Those two yang modules are built into pyang...

Kent

**Comment by kwatsen** [comment]
solution accepted.
