### ISSUE TITLE
Move brski-cloud YANG to this document

### ISSUE THREAD

**Issue by mcr** [anima-wg/voucher#23]
draft-ietf-anima-brski-cloud has YANG extensions to vouchers, which need to move to RFC8366bis.

**Comment by EskoDijk** [comment]
I see the 2 fields are already moved in -07, however the SID values aren't assigned to the 2 new fields. (This issue could be kept open for fixing this.)

**Comment by mcr** [comment]
closed in 74d049e0048323bbce76af32687f40119625d1f7.
