### ISSUE TITLE
jws vs pkcs7

### ISSUE THREAD

**Issue by pritikin** [anima-wg/voucher#6]
this is still open

**Comment by pritikin** [comment]
kent: points out that jws doesn't support transport of revocation objects

**Comment by pritikin** [comment]
not supporting transport of revocation object is a benefit (in my opinion)

**Comment by pritikin** [comment]
Proposed resolution for closing this:

Modify section 6 to indicate: "The voucher signature method does not impact the internal voucher contents. 
 Unless otherwise signaled the voucher signing method is.... pkcs7 etc. Methods of signaling alternative signature methods are out-of-scope of this document, but documents that leverage vouchers can provide this signaling. For example they might instruct that JWS signing is the signature method in their work."

This allows 'voucher' to be complete but flexible so that the 'voucher' document doesn't need to be updated if BRSKI or something else comes along and decides to signal, via mime-type for example, that JWS signed vouchers are in use. 

I'll update BRSKI back to pkcs7 for now but via the mime types indicate that future formats might be seen (e.g. registrar should be prepared to deal with mime types it doesn't understand)

**Comment by kwatsen** [comment]
Works for me.  Probably the best we can do given the time.

**Comment by toerless** [comment]
Resolved
